### ISSUE TITLE
Perf: not cleaning unpacked .siva files makes things slower

### ISSUE THREAD

**Issue by bzz** [src-d/engine#132]
There is empirical evidence of what supposed to be optimization, may be causing a performance degradation - if cleaning unpack .siva files is skipped , it makes job run much slower (like 2x)

**Comment by erizocosmico** [comment]
More detailed explanation of what happened:

- Using skip cleanup optimization the first run was way slower than without it.
- Subsequent runs took as long as without the optimization

**Comment by mcarmonaa** [comment]
After `skipCleanup` option fix, I performed test in local with the [100 samples of siva files](https://drive.google.com/open?id=0BxNVgwtOUkMUaG5wbmpnRklmMEk)  and I couldn't appreciate performance differences:

```text
LOCAL
---------

- skip_cleanup=False
- Wall time:
first time it ran: 4.92s
second time it ran: 2.65s

- skip_cleanup=True
- Wall time:
first time it ran: 5.06s
second time it ran: 2.24s
```

The snippet of code from the `engine-jupyter` notebook example which was used for testing was:

```python
%%time
engine.repositories.filter("is_fork = false")\
.select("id").distinct()\
.count()
```

Trying to run the same test in the cluster fails with `java.io.IOException: No space left on device` because not removing siva files fills the disk.

**Comment by ajnavarro** [comment]
Can we close this issue then?
