### ISSUE TITLE
Engine backed by a database

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#166]
Prepare the engine to be able to get all the metadata from:
- Repositories
- Commits
- References
- Trees

And be able to save them in a specific datasource. After that, add a special method on the engine to change the input of the data from siva files to the specified datasource. Example:

Back all the data to a specified source:
`engine.backToSource("[SOURCE_STRING]", [SOURCE_OPTIONS])`

Use this backed data to obtain the needed metadata:
`engine.fromSource("[SOURCE_STRING]", [SOURCE_OPTIONS]).getRepositories...`

Sources can be parquet, csv, json, jdbc connection, or any that already implement the correct traits as a DataSource with write options.

**Comment by erizocosmico** [comment]
I think we will need to change the  API a little bit. Depending on the datasource, we will need some kind of parameter per table. For example, we can't pass as `dbtable` to `jdbc` datasource a name because there is more than one table being written.

Maybe we ask for a callback that given a table name generates properties for that table.

Something like:

```scala
engine.backToSource("csv", opts, (table) => Map("path" -> s"${table}.csv"))
engine.backToSource("jdbc", opts, (table) => Map("dbtable" -> table))
```

We could even provide higher-level wrappers around common datasources such as jdbc for default values.

```scala
engine.backToJdbc(url, opts)
engine.backToJSON(basePath, opts)
```

Btw, we use arrays as types inside our dataframes, so csv will not work for most of the tables.

**Comment by erizocosmico** [comment]
Plan of action:

- [ ] Implement ENIP-001

Plan of action will expand once ENIP-001 is implemented and its performance tested.

**Comment by erizocosmico** [comment]
# Comparison between using database with metadata and reading raw siva file

Used the 100 siva files dataset.

- write to db: 1m17s

## Without metadata

- count repos: 7s180ms
- count refs (2 queries): 8s118ms
- count commits (2 queries): 10s282ms
- count tree entries of first ref commit: 5s46ms
- count blobs of first ref commit: 7s955ms

## With metadata

- count repos: 2s73ms
- count refs (2 queries): 4s648ms
- count commits (2 queries): 5s210ms
- count tree entries of first ref commit: 18s54ms
- count blobs of first ref commit: 55s684ms until it crashed due to no space left on device, but wasn't nearly done

**NOTE:** testing with the tests dataset shows that for small amount of repos, metadata is much slower even for things that are not related with blobs.

**Comment by erizocosmico** [comment]
Being superseded by https://github.com/src-d/engine/issues/239, https://github.com/src-d/engine/issues/238, https://github.com/src-d/engine/issues/240 and https://github.com/src-d/engine/issues/242
