### ISSUE TITLE
Row.uast is a list with len = 1

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#173]
When you execute `extract_uasts()`, `Row.uast` is a list with protobuf inside (size 1). I would expect it to be just protobuf.

**Comment by erizocosmico** [comment]
Yes, every column containing protobuf is a list. This is a trade-off we made for technical reasons. Do you miss documentation about that topic either in the python bindings or the tutorials/readme?

**Comment by erizocosmico** [comment]
@vmarkovtsev ping

**Comment by vmarkovtsev** [comment]
May I know what are the technical reasons?

Thing is, it confused Egor, Konst, Waren and myself. I wonder if there is a way to fix it.

For sure, having this explicitly stated somewhere in https://github.com/src-d/engine/blob/master/python/sourced/engine/engine.py#L402 would be great.

**Comment by ajnavarro** [comment]
All the UDFs that handle Nodes has the same input. Per example, you can execute `query_uast` UDF directly to an UAST or to the output of a previously executed `query_uast` result. If not, we are going to need UDFs doing the same, one of them to process a Node type, and another of them to process Array of Nodes type. So, instead of have:
- query_uast
- extract_tokens

We'll must have:
- query_uast
- extract_tokens
- query_uast_array
- extract_tokens_array

Having, in my opinion, a worst and complicated api.

**Comment by vmarkovtsev** [comment]
I see. Is there a way to receive a `Union<Node, Array<Node>>` and wrap the former into `Array<Node>` after figuring out the exact type? Using Scala templates.

**Comment by ajnavarro** [comment]
UDF types in spark should represent a specific `StructType`. So it should be (in this case) `ByteArray` or `Array[ByteArray] `. There is no type to represent `Union[ByteArray, Array[ByteArray]]`

**Comment by vmarkovtsev** [comment]
We should rewrite Spark from scratch

**Comment by ajnavarro** [comment]
> We should rewrite Spark from scratch

Good luck! :P
