### ISSUE TITLE
Research how to improve the rooted-repository format on HDFS, to be able to read data faster.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#179]

**Comment by erizocosmico** [comment]
We could use bitmap indexes along a few other things described here: https://githubengineering.com/counting-objects/ but I'm not sure how feasible that will be adding HDFS to the mix.

We could also just use a packfile with the objects sorted using a dependency graph so that parents (parents as in deltas) are always before, to always read only up to required object(s).

Additional resources: 

- https://github.com/git/git/blob/master/Documentation/technical/bitmap-format.txt
- https://github.com/git/git/blob/master/Documentation/technical/pack-format.txt
- https://github.com/ajnavarro/jgit-hdfs/blob/b3e00269400df9d9e3581499991b77e611bc9abc/src/main/java/com/ajnavarro/git/hadoop/service/RepositoryDataServiceWriter.java (for HDFS integration)

**Comment by ajnavarro** [comment]
Another interesting approach: Pre-calculate [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph]) edges and keep them in memory when processing data.

Of course, we should explore a lot of edge cases and the amount of memory needed.

https://www.google.com/patents/US20080222114

**Comment by ajnavarro** [comment]
Another interesting approach: Pre-calculate [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph]) edges, read them from the rooted-repo, and keep them in memory when processing data.

Of course, we should explore a lot of corner cases and the amount of memory needed.

https://www.google.com/patents/US20080222114

**Comment by ajnavarro** [comment]
deprecated.
