### ISSUE TITLE
Check list of unhandledFilters to don't filter two times with all the existing filters.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#183]
In BaseRelation we have:
```
  /**
   * Returns the list of [[Filter]]s that this datasource may not be able to handle.
   * These returned [[Filter]]s will be evaluated by Spark SQL after data is output by a scan.
   * By default, this function will return all filters, as it is always safe to
   * double evaluate a [[Filter]]. However, specific implementations can override this function to
   * avoid double filtering when they are capable of processing a filter internally.
   *
   * @since 1.6.0
   */
  def unhandledFilters(filters: Array[Filter]): Array[Filter] = filters
```

we should override this method to return a list of already-not-supported filters on our datasource, to avoid filter two times per each filter operation.

**Comment by mcarmonaa** [comment]
This method takes in `Filter`s, but since we are building engine on top of `SQL spark` our filters come up as `Expression`s so there are divergences between the filters `unhandledFilters` catches and the expressions we are receiving in the `buildScan` method.

Also spark performs optimizations which transform a lot the queries, so we can not be sure about what filters eventually we will be able to handle at sources level for the moment.

**Comment by erizocosmico** [comment]
Should we close this, then? @mcarmonaa @ajnavarro
