### ISSUE TITLE
[METADATA STORE] Testing in a real spark cluster

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#241]

**Comment by erizocosmico** [comment]
Update on this:

Tests on our cluster proved the current approach to be flawed and unusable in an environment where more than a single machine is needed for several reasons.

1. Node used to execute is also used as an executor (e.g. the node containing the spark shell used to do the query), which is something we don't want. We want only the workers to have jobs. There seems to not be any way to achieve this in Spark.
2. There is 0 guarantees that 1 and only 1 task will go to a single worker node. In any other possible case you end up with either data loss or data duplication, or both.

After more thinking we have determined that any approach that uses the workers as anything else that stateless computing power is fundamentally flawed. Same happens if we use the HDFS data nodes for the same purpose.

This task is left as paused until we come up with a better solution for storing the metadata and is implemented to be able to test it on a cluster. For now, there's not much else to test.

**Comment by erizocosmico** [comment]
I'm closing this, since it was done but unsuccessful.
