### ISSUE TITLE
srcd init doesn't work on Windows without specifing path

### ISSUE THREAD

**Issue by smacker** [src-d/engine#254]
https://user-images.githubusercontent.com/406916/53730085-2ee06900-3e77-11e9-8dfa-24a87b40d632.png

**Comment by se7entyse7en** [comment]
@smacker I actually managed to reproduce this but only by running `srcd web sql` without running `srcd init` first. Otherwise I wasn't able to reproduce it.

I was wondering whether we really want to initialize engine also by running `srcd web sql` if it hasn't been initialized yet, or whether we may want to enforce initializing using `srcd init` and then raise an error as `Engine has not been initialized yet. Please run 'srcd init [path]'`.

**Comment by smacker** [comment]
That is a good question. Kind of related discussion is here: https://github.com/src-d/engine/issues/273

**Comment by se7entyse7en** [comment]
I'm gonna consider this as pending until we decide or @src-d/product gives as an input. 👍

**Comment by carlosms** [comment]
In my opinion there are 2 tasks here:
- make `srcd web sql` work on windows without a previous `init`
- discussion to force a `srcd init`

The first one could be included in 0.11.0, as it is a bug that makes the windows executable work different as the linux one. What is the bug @se7entyse7en? Is it easy to fix?

And the second one I think does not fit in between a RC and the final release. Even if we decide to change it, it should probably go into a 0.12.0.

**Comment by se7entyse7en** [comment]
@carlosms I guess that we just have to copy the same path replacement, it should be something really easy to do. I'm just finishing a thing for integration testing, then I'll look into this.

**Comment by se7entyse7en** [comment]
I've created a separated issue for forcing initialization: #304.
