### ISSUE TITLE
LIMIT query does not finish

### ISSUE THREAD

**Issue by bzz** [src-d/engine#267]
In application, we use `limit` to test it on sub-set of repositories.

In case more than 1 siva file in `/path/to/siva-files`

`$SPARK_HOME/bin/spark-shell --packages "tech.sourced:engine:0.1.12"`

```scala
import tech.sourced.engine._
val engine = Engine(spark, "/path/to/siva-files")
val repos = engine.getRepositories.limit(1)
val headRefs = repos.getReferences.filter("name = 'refs/heads/HEAD' OR name = 'HEAD'")
headRefs.getCommits.getFirstReferenceCommit.getFiles.show()
```

never finishes, producing

```
17/12/18 15:36:39 WARN GitOptimizer: Join cannot be optimized. Invalid node: GlobalLimit 1
+- LocalLimit 1
   +- Project [id#1703]
      +- Relation[id#1703,urls#1704,is_fork#1705] GitRelation(org.apache.spark.sql.SparkSession@38c464df,StructType(StructField(id,StringType,false), StructField(urls,ArrayType(StringType,false),false), StructField(is_fork,BooleanType,true)),None,Some(repositories))

17/12/18 15:36:39 WARN GitOptimizer: Join cannot be optimized. Invalid node: LocalLimit 1
```
or in 4Gb RAM machine `java.io.IOException: No space left on device`.

It might, or might not have to do anything with #156

**Comment by ajnavarro** [comment]
Doing a limit you are not allowing to the GitOptimizer to optimize the join. For more info see here: https://github.com/src-d/engine/issues/156#issuecomment-343449762

Limit as a last step of the chain, or filter by a specific repository.

**Comment by ajnavarro** [comment]
Sorry, I didn't realize that you saw #156

**Comment by bzz** [comment]
@ajnavarro before closing the issue, if that is something documented for the user - could you please point me to that?

As we need to spend some time to work it wound and it was totally not obvious :/

**Comment by smacker** [comment]
From my point of view, it looks like a bug. Maybe lack of optimization is okay, but forever hanging for only 2 small repos is a problem.

**Comment by bzz** [comment]
As discussed offline \w @ajnavarro - it's not clear how to support it right now, so he suggested a better error reporting to be added, so it's communicate to the end-users better and fails fast.

**Comment by erizocosmico** [comment]
Not exactly what you're asking for but for these cases when you need to do this, it might be helpful to split the process in two (first query to retrieve the repositories with the limit) and then getting the rest of the stuff in a second query. There's a method specially designed for those kinds of usages, which is [`getBlobs`](https://engine.sourced.tech/v0.3.3/api/scala/#tech.sourced.engine.Engine@getBlobs(repositoryIds:Seq[String],referenceNames:Seq[String],commitHashes:Seq[String]):org.apache.spark.sql.DataFrame) directly on engine.

**Comment by smacker** [comment]
Thanks for the tip!

we actually solved it exactly as you described: https://github.com/src-d/gemini/blob/master/src/main/scala/tech/sourced/gemini/Gemini.scala#L28
First we get repos and then we use filter.

My point is I would love to have an exception if the engine can't do something instead of silent "hanging".
Not a top priority for sure, but it would help users of engine (includes me).

**Comment by erizocosmico** [comment]
We changed that to an exception, but that's really limiting, so it's been reverted. It's not that the engine _can't_ do it, it can. It will just be slow because it can't add optimizations, which does not mean it should be an exception because there are other cases that are not optimizables that you still want to support (`InMemoryRelation`s, for example).
