### ISSUE TITLE
incorrect string port in config produces unclear error

### ISSUE THREAD

**Issue by smacker** [src-d/engine#272]
```
$ ./srcd init
FATA[0000] Config file does not follow the expected format: yaml: unmarshal errors:
  line 9: cannot unmarshal !!str `asd` into int
```

**Comment by carlosms** [comment]
How can be improve it, what would you expect it to say?

**Comment by smacker** [comment]
I would expect it to point on the field that has incorrect value.

Something similar to default json error: `json: cannot unmarshal string into Go struct field Config.Port of type int` would be enough most probably.

Example: https://play.golang.org/p/ALKuOUSvr6s

**Comment by dpordomingo** [comment]
From that error message, it is not said which file caused the error; it should be said so

**Comment by se7entyse7en** [comment]
Unfortunately, go-yaml doesn't expose anything about the error except for the string that is already being printed. There are also a couple of issue about that:
- https://github.com/go-yaml/yaml/issues/343
- https://github.com/go-yaml/yaml/issues/108

In theory from the second link:

> The upcoming and in-progress yaml.v3 will offer an intermediate representation that will allow that kind of detail to be exposed.

but by looking at the contributions the project seems stale.

I'd add the file that caused the error as @dpordomingo said. If we want to also add information about the field name we could add a layer on top of go-yaml and extract the field by actually reading the file given the line number  or fork go-yaml 😄.

The first approach seems a bit hacky, but should be doable. The problem is that I noticed that sometimes the line number is not correct, I guess because the library expects the yaml to be in dense format (no new lines).

WDYT?

**Comment by smacker** [comment]
Let's add only filename now. Field issue will be fixed "automatically" with new go-yaml release. And we have dependabot to notify us about new version.
