### ISSUE TITLE
Commit counts returns references count instead

### ISSUE THREAD

**Issue by eiso** [src-d/engine#325]
## Expected Behavior

The expected behavior is 160,666 commits returned. I discovered this bug when benchmarking against my personal project to understand the MapReduce challenges better, see [results](https://i.imgur.com/JtiBFmD.png).

## Current Behavior
```from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "/repositories", "standard")

engine.repositories.references.commits.count()
```

**returns: 564**

What I am fairly certain is happening is a LEFT JOIN on references instead of commits. Returning the total # of refs, not commits. 

## Steps to Reproduce (for bugs)
1.
```
git clone https://github.com/python/cpython
git clone https://github.com/spring-projects/spring-framework
git clone https://github.com/apache/spark
```
2. Run the above command on the engine

## Your Environment (for bugs)
* Version used: v0.4.1
* Operating System and version: run from the official container

**Comment by erizocosmico** [comment]
Can you try substituting commits by all_reference_commits?
On Sat, 27 Jan 2018 at 22:59, Eiso Kant <notifications@github.com<mailto:notifications@github.com>> wrote:
Expected Behavior

The expected behavior is 160,666 commits returned. I discovered this bug when benchmarking against my personal project to understand the MapReduce challenges better, see results<https://i.imgur.com/JtiBFmD.png>.

Current Behavior

from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "/repositories", "standard")

engine.repositories.references.commits.count()


returns: 564

What I am fairly certain is happening is a LEFT JOIN on references instead of commits. Returning the total # of refs, not commits.

Steps to Reproduce (for bugs)

  1.

git clone https://github.com/python/cpython
git clone https://github.com/spring-projects/spring-framework
git clone https://github.com/apache/spark


  1.  Run the above command on the engine

Your Environment (for bugs)

  *   Version used: v0.4.1
  *   Operating System and version: run from the official container

**Comment by eiso** [comment]
Judging by the 30 mins it's been running already, it is working ;)

**Comment by eiso** [comment]
It returned the following value, which I assume is so high because I did not add distinct(): *19949168*

**Comment by eiso** [comment]
I decided to finish implementing the equivalent of `all_reference_commits`* to verify the # returned by the engine.

Please find my results [here](https://i.imgur.com/YkLJuCk.png)**.  The number I returned is: _17,539,364_

@erizocosmico I'd be curious to know where the discrepancy comes from in the numbers.

\* `all_reference_commits = for each reference, get the commit and all of the commits' children`

**Comment by erizocosmico** [comment]
Hard to tell from those numbers alone. I'd need a reproduction case with all the repos you were using to get them.

If you want to get all unique commits you can do:

```
engine.repositories.references.all_reference_commits.drop('repository_id', 'reference_name').distinct()
```

Otherwise there are repeated rows because they have different `reference_name` and `repository_id`.

**Comment by erizocosmico** [comment]
Any updates on this?
