### ISSUE TITLE
Measure all the steps to be able to find bottlenecks

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#344]
Measure all the steps needed to get data from a repository.

- Read data from HDFS and copy to local drive
- Uncompress siva content and copy it to a temporal folder
- Create repository instance to read data from packfiles and other files in the repository
- get UAST from blobs
- get LANG from blobs
- Time used on spark processing rows
- Remove temporal files from a local file system
- Time serializing data between spark nodes

**Comment by smola** [comment]
I did a profiling session locally (no HDFS) with 1264 siva files from the PGA dataset where I found two major bottlenecks:
* reading repo configuration (fixed here: https://github.com/src-d/engine/pull/346)
* siva unpacking

I'm going to repeat the process in a proper cluster with HDFS.

**Comment by smola** [comment]
With 2k siva files on HDFS, for my reference query: `engine.getRepositories.getReferences.filter('name === "refs/heads/HEAD").getAllReferenceCommits.filter('message.contains("Initial commit")).select('repository_id, 'message).show`

* ~50% of the time was spent copying from HDFS, that's to be expected since we were not using HDFS data locality on Spark.
* Siva unpacking took ~9%.
* The already fixed bug on reading repo configuration took less than 1%.

Also, a few executors took double than the others to finish (the same happened with more simple queries). That suggests that we need more partitions and with a more even distribution of data.

So, I would prioritize the following (from the most to the least prioriatary):
1. Tune default partitioning.
2. Ensure we take advantage of data locality, reducing network traffic and reading directly form disk if possible.
3. Do not unpack siva files, use a sivafs implementation.
4. Profile again and micro-optimize ;-)

**Comment by smola** [comment]
Closing this after initial assesment. We have some optimization work ahead, as well as the instrumentation tasks to improve measurements.
