### ISSUE TITLE
Push Docker images for development versions (master)

### ISSUE THREAD

**Issue by smola** [src-d/engine#366]
## Expected Behavior

`dev-<commit>` tags for engine-jupyter should be available at Docker Hub.

## Current Behavior
They are not pushed.

## Possible Solution
Use functionality already available at src-d/ci:
https://github.com/src-d/ci/blob/beb8af9aa6417e701751858d449bbdfe6f3ee3bd/Makefile.main#L171

## Context
This will make it easier to test latest development version on our k8s clusters.

**Comment by ajnavarro** [comment]
Right now we are using `sbt-git` (https://github.com/sbt/sbt-git) plugin to generate the versions. We need to change a bit the actual output that is the default one.

**Comment by erizocosmico** [comment]
@smola AFAIK, src-d/ci does not handle the dev-xxxx workflow. It has two tasks for this: `docker-push`, which exits on master and `docker-push-latest` that updates the `latest` tag even in master. Is updating latest something we might want? Otherwise we can't use src-d/ci for this (unless we add that feature there), but a custom rule that does the upload to `dev-xxxxxx`.

**Comment by ajnavarro** [comment]
We should improve this solution, because right now we are generating the docker container on each PR too, but is not uploaded:
```
Successfully built 8cd877f261a3
Successfully tagged srcd/engine-jupyter:dev-6d56ad3-dirty
Makefile:143: *** "push disabled for pull-requests".  Stop.
```

To make Travis faster, maybe we can use [conditional builds](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/)
