### ISSUE TITLE
 gitbase port conflict when using the Engine

### ISSUE THREAD

**Issue by vcoisne** [src-d/engine#72]
Bug faced by one of our users and reported via drift: 

Command `srcd web sql`

ATA[0075] could not start gitbase web client at port 8080: rpc error: code = Unknown desc = could not create srcd-cli-gitbase: could not start container: srcd-cli-gitbase: Error response from daemon: driver failed programming external connectivity on endpoint srcd-cli-gitbase (b70dc2431912a12797b3bef7f324df3902e35543af79e5642d5ff457c293e33b): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated

User checked `docker ps -a` and I doesn't see port 3306 in use
On his os nothing is on that port: lsof -i :3306
Docker daemon is not hung

In gitbase> prompt
He tries typing show tables;
and SELECT * FROM repositories;

gitbase> SELECT COUNT(*) FROM repositories;
rpc error: code = Unknown desc = could not create srcd-cli-gitbase: could not start container: srcd-cli-gitbase: Error response from daemon: driver failed programming external connectivity on endpoint srcd-cli-gitbase (22454bed8c5fdbf21a681030e71ea76de0aaaa59fcbb79f444c92514d99c7863): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated

Seems like there is no flag to change the gitbase port. Can someone make it a flag and tag a new release for this ?

cc @campoy @eiso

**Comment by campoy** [comment]
I don't have the bandwidth to fix this right now, unfortunately.

I thought it would be a simple fix but it requires thinking about UX too, and a lot.

Rather than using a flag (which would be required on potentially every command execution) we might consider the following options:

- an environment variable int he style of `SRCD_SQL_PORT` `SRCD_PARSE_PORT`  etc
- a config file (`.srcd` maybe?) where one can set the corresponding port
- port++ when the default port is busy until we find one that is available

Additionally, I think not exposing any port by default should reduce the possibility of port conflict (just using docker networks to connect across containers).

What do you think, @ajnavarro ?

**Comment by smola** [comment]
> Additionally, I think not exposing any port by default should reduce the possibility of port conflict (just using docker networks to connect across containers).

+1 to not exposing the port by default.

Adding a flag to gitbase to choose where to bind (IP and port, even UNIX socket) would make sense too.

**Comment by campoy** [comment]
I think the best solution is the config file, since the flags would otherwise need to be passed for every command or handling which flags apply to what command will become a nightmare.

I am planning to meet with @marnovo about this and other improvements to the engine soon and will come back with what interaction mode makes more sense.

**Comment by carlosms** [comment]
Related to #56.

**Comment by bzz** [comment]
just stumbled up on this

```
./srcd sql "SHOW tables;" 
2018/11/23 15:16:14 rpc error: code = Unknown desc = could not create srcd-cli-bblfshd: could not start container: srcd-cli-bblfshd: Error response from daemon: driver failed programming external connectivity on endpoint srcd-cli-bblfshd (f8f1a52f2e270b7c2d01bbd8b6935f8a8244b8d989ee68458616376b9cf6afee): Bind for 0.0.0.0:9432 failed: port is already allocated
```

may be at least more friendly error message could be in order here? Like advising user to check if another bblfhsd is running and turn it down?

**Comment by carlosms** [comment]
Done in #236, next release will include a config file to setup the ports.
